fix: fromScreen not using viewport scale
kaplayjs/kaplay pull request #436
Opened 2024-10-06 14:08 UTC by lajbel

## Description

### Issues or related

- Related Issue #
- Closes #325

2024-10-06 14:14 UTC, mflerackers requested changes
This is wrong. World and local have nothing to do with viewport scale.
Viewport scale only makes sense between screen and world.

2024-10-06 14:17 UTC, mflerackers commented
Additionally, you don't want to divide each time, it is better to store 1 / factor and multiply instead.

2024-10-06 19:42 UTC, dragoncoder047 commented
So scale is fine now, it's stretch that is bugged. If `letterbox: true` then it works since the canvas's aspect ratio is as specified. `stretch` makes it not be as specified, so it gets off.

```js
kaplay({
    scale: 3,
    width: 20,
    height: 40,
    stretch: true
});

const x = add([
    anchor("center"),
    circle(3),
    color(RED),
    pos(),
]);

getTreeRoot().use(pos());

onMouseMove(pos => {
    x.pos = getTreeRoot().fromScreen(pos);
});
```

2024-10-06 22:37 UTC, mflerackers commented
Yeah, when stretch is used, you no longer have a uniform scale. You need a vec2 in that case.

2024-10-13 22:30 UTC, lajbel commented
> So scale is fine now, it's stretch that is bugged. If `letterbox: true` then it works since the canvas's aspect ratio is as specified. `stretch` makes it not be as specified, so it gets off.
> 
> ```js
> kaplay({
>     scale: 3,
>     width: 20,
>     height: 40,
>     stretch: true
> });
> 
> const x = add([
>     anchor("center"),
>     circle(3),
>     color(RED),
>     pos(),
> ]);
> 
> getTreeRoot().use(pos());
> 
> onMouseMove(pos => {
>     x.pos = getTreeRoot().fromScreen(pos);
> });
> ```

The question is if there's an user case using only Stretch without letterbox

2024-10-30 20:28 UTC, niceEli commented
resolved conflicts in commit 894d9df6d65baa497d017fb09db200cb39066eae

2024-10-30 20:30 UTC, niceEli commented
no idea for fail
should of worked properly

2025-03-12 12:01 UTC, closed without merging