fix: add return if static to physics apply force functions
kaplayjs/kaplay pull request #443
Opened 2024-10-09 21:05 UTC by dragoncoder047

I noticed by accident that if a static body collides with an area effector, then the velocity of the static body will still be modified and the static body will fly off into the ether. But it's static, it shouldn't move. This fixes that.

```ts
kaplay();

add([
    pos(10, 10),
    rect(100, 100),
    color(BLUE),
    area(),
    areaEffector({ forceAngle: 0, forceMagnitude: 10 }),
]);

// Wheeeeeee!! I am static but still get pushed!
add([
    pos(20, 20),
    rect(100, 10),
    color(RED),
    area(),
    body({ isStatic: true }),
]);
```

2024-10-30 16:14 UTC, niceEli requested changes
maybe there could be an error like "cannot add a force too a static body" or something like that, other than that it seems good, if you feel it shouldnt have an error then just say and ill approve

2024-10-30 16:15 UTC, niceEli commented
wait sorry nvm to that i reread what you wrote

2024-10-30 16:15 UTC, niceEli approved these changes

2024-11-28 00:58 UTC, mflerackers approved these changes

2024-11-28 01:57 UTC, lajbel commented
This is both versions? We could say it was a bug?

2024-11-29 15:52 UTC, merged