jsdoc example for onadd
kaplayjs/kaplay pull request #474
Opened 2024-10-22 16:40 UTC by amyspark-ng

before submitting a pull request

2024-10-22 17:13 UTC, imaginarny commented
There shouldn't be the same example for top level `onAdd` and `gameObjRaw` method `onAdd`. You are missing use cases on top level one as we discussed on Discord.

2024-10-23 13:07 UTC, lajbel commented
You forgot some ;

2024-10-23 16:04 UTC, amyspark-ng commented
> There shouldn't be the same example for top level `onAdd` and `gameObjRaw` method `onAdd`. You are missing use cases on top level one as we discussed on Discord.

Could you better explain? so that i can put i was checking discord and i really don't remember what we talked about

2024-10-23 17:25 UTC, niceEli requested changes
semicolons, then its perfect

2024-10-23 17:25 UTC, niceEli commented on src/types.ts
> +     *     play("bling")
pls add semicolons

2024-10-23 23:23 UTC, imaginarny commented
> Could you better explain? so that i can put i was checking discord and i really don't remember what we talked about
— @amyspark-ng 

There is a top level `onAdd` and `onAdd` that is a method of `gameObjRaw`. Top level can either accept a tag and action as args, or just an action. You have an example for a tag option, which is ok. But [the next one, for the action only](https://github.com/kaplayjs/kaplay/pull/474/files#diff-c54113cf61ec99691748a3890bfbeb00e10efb3f0a76f03a0fd9ec49072e410aR1277), should be something like this:

```js
// Runs when an object is added to the scene.

onAdd((obj) => {
    obj.pos = obj.sprite == "bean" ? center() : vec2(rand(0, width()), rand(0, height()));
})

add([sprite("bean")]); // centered pos
add([sprite("bobo")]); // random pos
```

Instead of what you have:

```js
// Runs when an specific object is added to the scene.

let bean = make([
    sprite("bean"),
    pos(),
])

bean.onAdd(() => {
    bean.pos = center();
})

add(bean);
 ```

Point is that it's not called on an object, instead uses `obj: GameObj` param from action. Also, notice the difference in the description. First runs when an object (any) is added to the scene, not a specific one as in the case for `gameObjRaw` (there is a typo too, should be ~an~ a specific).

Then you have this example 2nd time also for `gameObjRaw` [there](https://github.com/kaplayjs/kaplay/pull/474/files#diff-c54113cf61ec99691748a3890bfbeb00e10efb3f0a76f03a0fd9ec49072e410aR4285), which is right.

Hope it makes more sense now.

2024-10-24 02:08 UTC, amyspark-ng commented
hopefully this is good now

2024-10-24 02:15 UTC, amyspark-ng commented
WAIT don't merge this, https://github.com/kaplayjs/kaplay/pull/477 is way better

2024-10-24 22:26 UTC, amyspark-ng commented
closed for https://github.com/kaplayjs/kaplay/pull/477, which is 10 times better

2024-10-24 22:26 UTC, closed without merging