docs: Added many examples for on events
kaplayjs/kaplay pull request #534
Opened 2024-11-23 20:24 UTC by tristanperrow

See [#477](https://github.com/kaplayjs/kaplay/pull/477) for more details.

2024-11-25 13:39 UTC, lajbel requested changes

2024-11-25 13:39 UTC, lajbel commented on src/types.ts
> +     * @param tag - The tag for which the event runs.
The tag to listen for is what is most used

2024-11-25 13:39 UTC, lajbel commented on src/types.ts
> +     * @param action - The callback that runs when an object is added.
callback -> function

2024-11-25 13:39 UTC, lajbel commented on src/types.ts
> +     * @param tag - The tag for which the event runs.
-> listen for

2024-11-25 17:51 UTC, tristanperrow commented
Should be all fixed now

2024-11-26 02:24 UTC, lajbel approved these changes

2024-11-26 02:25 UTC, lajbel commented
Great! Thank you so much

2024-11-26 02:25 UTC, merged