feat: add k.cancel()
kaplayjs/kaplay pull request #545
Opened 2024-11-28 13:47 UTC by neverUsedGithub

## Description
Adds support for `k.cancel()`, a new way to cancel events in KAPLAY. As discussed on Discord, `k.cancel` is a method to signify that it has an "action", to maybe help beginners better understand it.

```js
onKeyPress((key) => {
    if (key === "q") return k.cancel();
});
```

2024-11-28 21:52 UTC, niceEli approved these changes

2024-11-28 23:49 UTC, lajbel requested changes

2024-11-28 23:49 UTC, lajbel commented on src/types.ts
> +    cancel: () => Symbol,
Use the correct format described in Contributing.md

2024-11-29 15:51 UTC, lajbel approved these changes

2024-11-29 15:51 UTC, merged